-- ============================================================================
-- Script 04: Gestion des droits d'accès (Partie 3)
-- BDA 2025 - Projet Agence de Location
-- ============================================================================
-- Description: Création de la table ACCESS et gestion des utilisateurs
-- Ordre d'exécution: 4ème script
-- ============================================================================

SET ECHO ON
SET SERVEROUTPUT ON

PROMPT ============================================================
PROMPT Partie 3.1: Création de la table ACCESS
PROMPT ============================================================

-- Supprimer si existe
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ACESS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE ACESS (
    user_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login        VARCHAR2(100) UNIQUE NOT NULL,
    password     VARCHAR2(64) NOT NULL,  -- MD5 en hexadécimal = 32 caractères
    access_level CHAR(1) DEFAULT 'L' 
                 CHECK (access_level IN ('L','E','U','D','T'))
);

COMMENT ON TABLE ACESS IS 'Table de contrôle d''accès';
COMMENT ON COLUMN ACESS.user_id IS 'Identifiant unique auto-incrémenté';
COMMENT ON COLUMN ACESS.login IS 'Login de l''utilisateur';
COMMENT ON COLUMN ACESS.password IS 'Mot de passe hashé (MD5)';
COMMENT ON COLUMN ACESS.access_level IS 'Niveau d''accès: L=Lecture, E=Écriture, U=Update, D=Delete, T=Total';

PROMPT ✓ Table ACESS créée

PROMPT ============================================================
PROMPT Partie 3.2: Remplissage avec les clients
PROMPT ============================================================

-- Insérer les clients: login = nom.prenom, password = MD5 aléatoire
INSERT INTO ACESS (login, password, access_level)
SELECT 
    LOWER(c.Nom || '.' || c.Prenom) AS login,
    LOWER(STANDARD_HASH(DBMS_RANDOM.STRING('X', 16), 'MD5')) AS password,
    'L' AS access_level
FROM Client c;

PROMPT ✓ Clients ajoutés à la table ACESS

PROMPT ============================================================
PROMPT Partie 3.2: Ajout des propriétaires
PROMPT ============================================================

-- Insérer les propriétaires: login = email, access_level = 'E'
INSERT INTO ACESS (login, password, access_level)
SELECT 
    LOWER(p.email) AS login,
    LOWER(STANDARD_HASH(DBMS_RANDOM.STRING('X', 16), 'MD5')) AS password,
    'E' AS access_level
FROM Proprietaire p;

COMMIT;

PROMPT ✓ Propriétaires ajoutés à la table ACESS

PROMPT ============================================================
PROMPT Vérification des données ACCESS
PROMPT ============================================================

SELECT 
    access_level,
    COUNT(*) AS nombre_utilisateurs
FROM ACESS
GROUP BY access_level
ORDER BY access_level;

-- Afficher quelques exemples
PROMPT Exemples d'utilisateurs créés:
SELECT user_id, login, access_level, SUBSTR(password, 1, 10) || '...' AS password_hash
FROM ACESS
WHERE ROWNUM <= 10
ORDER BY access_level, user_id;

PROMPT ============================================================
PROMPT Partie 3.3: Création des rôles Oracle
PROMPT ============================================================

-- Créer les rôles (si erreur = déjà existants, c'est OK)
BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE READ_R';
    DBMS_OUTPUT.PUT_LINE('✓ Rôle READ_R créé');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1921 THEN  -- role already exists
            DBMS_OUTPUT.PUT_LINE('⚠ Rôle READ_R existe déjà');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE WRITE_R';
    DBMS_OUTPUT.PUT_LINE('✓ Rôle WRITE_R créé');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1921 THEN
            DBMS_OUTPUT.PUT_LINE('⚠ Rôle WRITE_R existe déjà');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE ADMIN_R';
    DBMS_OUTPUT.PUT_LINE('✓ Rôle ADMIN_R créé');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1921 THEN
            DBMS_OUTPUT.PUT_LINE('⚠ Rôle ADMIN_R existe déjà');
        ELSE
            RAISE;
        END IF;
END;
/

PROMPT ============================================================
PROMPT Attribution des privilèges aux rôles
PROMPT ============================================================

-- READ_R: Lecture seule
GRANT SELECT ON Proprietaire TO READ_R;
GRANT SELECT ON Client TO READ_R;
GRANT SELECT ON Voiture TO READ_R;
GRANT SELECT ON Location TO READ_R;
GRANT SELECT ON V_Client TO READ_R;
GRANT SELECT ON V_Client55 TO READ_R;

PROMPT ✓ Privilèges SELECT accordés à READ_R

-- WRITE_R: Lecture + Insertion + Modification
GRANT SELECT, INSERT, UPDATE ON Proprietaire TO WRITE_R;
GRANT SELECT, INSERT, UPDATE ON Client TO WRITE_R;
GRANT SELECT, INSERT, UPDATE ON Voiture TO WRITE_R;
GRANT SELECT, INSERT, UPDATE ON Location TO WRITE_R;

PROMPT ✓ Privilèges SELECT, INSERT, UPDATE accordés à WRITE_R

-- ADMIN_R: Tous les droits + WITH GRANT OPTION
GRANT ALL PRIVILEGES ON Proprietaire TO ADMIN_R WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON Client TO ADMIN_R WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON Voiture TO ADMIN_R WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON Location TO ADMIN_R WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ACESS TO ADMIN_R WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON V_Client TO ADMIN_R WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON V_Client55 TO ADMIN_R WITH GRANT OPTION;

PROMPT ✓ Tous les privilèges accordés à ADMIN_R

PROMPT ============================================================
PROMPT Partie 3.3: Exemples de création d'utilisateurs Oracle
PROMPT ============================================================

PROMPT NOTE: Les utilisateurs Oracle doivent être créés par un DBA (SYSTEM)
PROMPT Exécutez ces commandes en tant que SYSTEM pour créer les utilisateurs:
PROMPT 
PROMPT -- Utilisateur avec droits de lecture uniquement:
PROMPT CREATE USER user_lecture IDENTIFIED BY Pass123;
PROMPT GRANT CREATE SESSION TO user_lecture;
PROMPT GRANT READ_R TO user_lecture;
PROMPT 
PROMPT -- Utilisateur avec droits de modification:
PROMPT CREATE USER user_write IDENTIFIED BY Pass123;
PROMPT GRANT CREATE SESSION TO user_write;
PROMPT GRANT WRITE_R TO user_write;
PROMPT 
PROMPT -- Utilisateur avec tous les droits:
PROMPT CREATE USER user_admin IDENTIFIED BY Pass123;
PROMPT GRANT CREATE SESSION TO user_admin;
PROMPT GRANT ADMIN_R TO user_admin;
PROMPT 

PROMPT ============================================================
PROMPT Script de création automatique des utilisateurs de test
PROMPT ============================================================

-- Ce bloc PL/SQL génère le script SQL à exécuter en tant que SYSTEM
SET SERVEROUTPUT ON SIZE UNLIMITED

DECLARE
    CURSOR c_users IS
        SELECT login, access_level
        FROM ACESS
        WHERE ROWNUM <= 3;  -- Créer seulement 3 utilisateurs de test
    
    v_role VARCHAR2(30);
BEGIN
    DBMS_OUTPUT.PUT_LINE('-- ============================================');
    DBMS_OUTPUT.PUT_LINE('-- Script à exécuter en tant que SYSTEM/DBA');
    DBMS_OUTPUT.PUT_LINE('-- ============================================');
    DBMS_OUTPUT.PUT_LINE('');
    
    FOR r IN c_users LOOP
        -- Déterminer le rôle selon access_level
        CASE r.access_level
            WHEN 'L' THEN v_role := 'READ_R';
            WHEN 'E' THEN v_role := 'WRITE_R';
            WHEN 'U' THEN v_role := 'WRITE_R';
            WHEN 'D' THEN v_role := 'ADMIN_R';
            WHEN 'T' THEN v_role := 'ADMIN_R';
        END CASE;
        
        -- Générer les commandes SQL
        DBMS_OUTPUT.PUT_LINE('-- Utilisateur: ' || r.login || ' (niveau: ' || r.access_level || ')');
        DBMS_OUTPUT.PUT_LINE('CREATE USER "' || r.login || '" IDENTIFIED BY "Pass123Temp!";');
        DBMS_OUTPUT.PUT_LINE('GRANT CREATE SESSION TO "' || r.login || '";');
        DBMS_OUTPUT.PUT_LINE('GRANT BDA2025.' || v_role || ' TO "' || r.login || '";');
        DBMS_OUTPUT.PUT_LINE('');
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('-- Fin du script');
END;
/

PROMPT ============================================================
PROMPT Partie 3.4: Procédure de vérification des accès
PROMPT ============================================================

CREATE OR REPLACE PROCEDURE verifier_acces(
    p_username VARCHAR2,
    p_table VARCHAR2
) AS
    v_can_select NUMBER := 0;
    v_can_insert NUMBER := 0;
    v_can_update NUMBER := 0;
    v_can_delete NUMBER := 0;
BEGIN
    -- Note: Cette procédure doit être exécutée par l'utilisateur lui-même
    DBMS_OUTPUT.PUT_LINE('Vérification des droits pour ' || p_username || ' sur ' || p_table);
    DBMS_OUTPUT.PUT_LINE('-------------------------------------------------------');
    
    -- Vérifier SELECT
    BEGIN
        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM BDA2025.' || p_table || ' WHERE ROWNUM = 1';
        v_can_select := 1;
    EXCEPTION
        WHEN OTHERS THEN v_can_select := 0;
    END;
    
    DBMS_OUTPUT.PUT_LINE('SELECT: ' || CASE WHEN v_can_select = 1 THEN '✓ Autorisé' ELSE '✗ Refusé' END);
    
    -- Note: INSERT, UPDATE, DELETE nécessiteraient des tests en session utilisateur
    DBMS_OUTPUT.PUT_LINE('');
END;
/

PROMPT ============================================================
PROMPT Statistiques finales
PROMPT ============================================================

SELECT 'Total utilisateurs dans ACESS' AS statistique, COUNT(*) AS nombre
FROM ACESS
UNION ALL
SELECT 'Utilisateurs niveau L (Lecture)', COUNT(*)
FROM ACESS WHERE access_level = 'L'
UNION ALL
SELECT 'Utilisateurs niveau E (Écriture)', COUNT(*)
FROM ACESS WHERE access_level = 'E'
UNION ALL
SELECT 'Utilisateurs niveau U (Update)', COUNT(*)
FROM ACESS WHERE access_level = 'U'
UNION ALL
SELECT 'Utilisateurs niveau D (Delete)', COUNT(*)
FROM ACESS WHERE access_level = 'D'
UNION ALL
SELECT 'Utilisateurs niveau T (Total)', COUNT(*)
FROM ACESS WHERE access_level = 'T';

PROMPT ============================================================
PROMPT ✅ Script 04_access.sql exécuté avec succès
PROMPT ============================================================
PROMPT 
PROMPT Pour tester les droits d'accès:
PROMPT 1. Exécuter le script généré ci-dessus en tant que SYSTEM
PROMPT 2. Se connecter avec chaque utilisateur créé
PROMPT 3. Tester les opérations SELECT, INSERT, UPDATE, DELETE
PROMPT 
PROMPT Exemple de test:
PROMPT   sqlplus user_lecture/Pass123@XEPDB1
PROMPT   SELECT * FROM BDA2025.Client;  -- Devrait fonctionner
PROMPT   INSERT INTO BDA2025.Client ... -- Devrait échouer
PROMPT 
PROMPT Prochaine étape: Exécuter 05_plsql.sql
PROMPT 
